"""social_security_number_in_user_table

Revision ID: d134729f6ea4
Revises: e93cc08b787b
Create Date: 2019-09-18 11:32:10.975448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd134729f6ea4'
down_revision = 'e93cc08b787b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_security_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_security_number')
    # ### end Alembic commands ###
